version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
  app:
    container_name: app
    build: .
    command: uvicorn tasks:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - rabbitmq
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - app
  flower:
    image: mher/flower
    build: ./
    command: celery -A celery_worker flower
    ports:
      - 5555:5555
    depends_on:
      - app
      - rabbitmq
      - celery_worker
